# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='isOpen',
            field=models.BooleanField(default=True, verbose_name='Open?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_description',
            field=models.CharField(max_length=255, verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.IntegerField(verbose_name='SKU'),
        ),
    ]
